language: java
sudo: false

env:
  global:
    - TRAVIS_TAG=1.0.0-test

jobs:
  include:
  - stage: test
    jdk: openjdk9
    script: mvn clean test
  - jdk: openjdk10
    script: mvn clean test
  - jdk: openjdk11
    script: mvn clean test
  - jdk: openjdk12
    script: mvn clean test
  - stage: release_jdk9
    jdk: openjdk9
    script: mvn clean package
    before_deploy:
      - export TRAVIS_TAG=$TRAVIS_TAG-jdk9
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      overwrite: true
      file:
        - perses-agent.jar
        - Injector/target/perses-injector-jar-with-dependencies.jar
      skip_cleanup: true
      on:
        repo: nicolasmanic/perses
        branch: master
        tags: true
  - stage: release_jdk10
    jdk: openjdk10
    script: mvn clean package
    before_deploy:
      - export TRAVIS_TAG=$TRAVIS_TAG-jdk10
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      overwrite: true
      file:
        - perses-agent.jar
        - Injector/target/perses-injector-jar-with-dependencies.jar
      skip_cleanup: true
      on:
        repo: nicolasmanic/perses
        branch: master
        tags: true
  - stage: release_jdk11
    jdk: openjdk11
    script: mvn clean package
    before_deploy:
      - export TRAVIS_TAG=$TRAVIS_TAG-jdk11
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      overwrite: true
      file:
        - perses-agent.jar
        - Injector/target/perses-injector-jar-with-dependencies.jar
      skip_cleanup: true
      on:
        repo: nicolasmanic/perses
        branch: master
        tags: true
  - stage: release_jdk12
    jdk: openjdk12
    script: mvn clean package
    before_deploy:
      - export TRAVIS_TAG=$TRAVIS_TAG-jdk12
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      overwrite: true
      file:
        - perses-agent.jar
        - Injector/target/perses-injector-jar-with-dependencies.jar
      skip_cleanup: true
      on:
        repo: nicolasmanic/perses
        branch: master
        tags: true