language: java
sudo: false

env:
  global:
    - TRAVIS_TAG=0.9.0

jobs:
  include:
  - stage: test
    jdk: openjdk8
    script: mvn clean test
  - stage: release_jdk9
    if: branch = JDK8
    jdk: openjdk8
    script: mvn clean package
    before_deploy:
      - export TRAVIS_TAG=$TRAVIS_TAG-jdk8
    deploy:
      provider: releases
      name: $TRAVIS_TAG
      api_key: $GITHUB_TOKEN
      overwrite: true
      file:
        - perses-agent.jar
        - Injector/target/perses-injector-jar-with-dependencies.jar
        - PersesUI/target/perses.jar
      skip_cleanup: true
      on:
        repo: nicolasmanic/perses
        tags: true
