language: java

stages:
  - test
  - release

jobs:
  include:
    - state: test
      - jdk_switcher use openjdk9
      script: mvn clean test
      - jdk_switcher use openjdk10
      script: mvn clean test
      - jdk_switcher use openjdk11
      script: mvn clean test
    - jdk_switcher use openjdk12
      script: mvn clean test